### ISSUE TITLE
no RIL 

### ISSUE THREAD

**Issue by rishabharidas** [ninetail-chocolate/Xtended_device_motorola_msm8953-common#1]
i just installed your ROM when i saw it in the androidfilehost. it booted perfectly fine. but there was no RIL

**Comment by ninetail-chocolate** [comment]
hello rishabharidas.
That's right.
I am currently working on a fix for the RIL.
If you have any solution, please let me know.
P.S. Thanks for trying my test build.

**Comment by rishabharidas** [comment]
if you like you can join 
https://t.me/joinchat/CsiG0BrHGshCB8Nr92ZNkA (this is a group for albus developers)
it would be a great pleasure.
some of the developers up there has seen these kind of issue while creating pie ROMS for albus from nothing. and was able to make it fix and bring back albus

**Comment by rishabharidas** [comment]
and please let me know if the issue is fixed and a new build is ready. the ROM was super smooth
@rishabharidas  <-- telegram

**Comment by ajaikumarnadar** [comment]
> hello rishabharidas.
> That's right.
> I am currently working on a fix for the RIL.
> If you have any solution, please let me know.
> P.S. Thanks for trying my test build.

Hi,

This issue was initially faced by me as well and I reported it to @Jeangraff30 and he fixed it right away. Maybe you guys should work together :)

What do you say?

You may join the group where Jean is also there... https://t.me/z2play
